require('dotenv').config();
const mongoose = require('mongoose');
const bcrypt = require('bcryptjs');

const connectDB = require('./config/db');
const User = require('./models/User');
const Category = require('./models/Category');
const MenuItem = require('./models/MenuItem');

const categories = [
  { name: 'Quick Bites', slug: 'quick-bites', icon: '🍟', displayOrder: 1 },
  { name: 'Loaded Fries', slug: 'loaded-fries', icon: '🧀', displayOrder: 2 },
  { name: 'Crispy chicken', slug: 'crispy-chicken', icon: '🍗', displayOrder: 3 },
  { name: 'Burger', slug: 'burger', icon: '🍔', displayOrder: 4 },
  { name: 'Sandwich', slug: 'sandwich', icon: '🥪', displayOrder: 5 },
  { name: 'Roll & Wrap', slug: 'roll-and-wrap', icon: '🌯', displayOrder: 6 },
  { name: 'Korean', slug: 'korean', icon: '🍜', displayOrder: 7 },
  { name: 'Pasta & Pulao', slug: 'pasta-and-pulao', icon: '🍝', displayOrder: 8 },
  { name: 'Mojitos', slug: 'mojitos', icon: '🍹', displayOrder: 9 },
  { name: 'Milkshakes', slug: 'milkshakes', icon: '🥤', displayOrder: 10 },
];

const getMenuItems = (catMap) => [
  // ── Quick Bites ──
  {
    name: 'French Fries',
    description: 'Crispy golden fries seasoned with classic salt',
    price: 99,
    category: catMap['quick-bites'],
    imageUrl: '/quick-bites/French fries.jpeg',
    tags: ['crispy', 'snack', 'veg'],
    isVeg: true,
    isBestseller: true,
    preparationTime: 8,
  },
  {
    name: 'Peri Peri Fries',
    description: 'Fries tossed in fiery peri peri spice blend',
    price: 120,
    category: catMap['quick-bites'],
    imageUrl: '/quick-bites/Peri peri fries.jpeg',
    tags: ['spicy', 'peri-peri', 'veg'],
    isVeg: true,
    isBestseller: true,
    preparationTime: 8,
  },
  {
    name: 'Veg Nuggets',
    description: 'Crunchy veggie nuggets served with dipping sauce',
    price: 149,
    category: catMap['quick-bites'],
    imageUrl: '/quick-bites/Veg Nuggets.jpeg',
    tags: ['veg', 'nuggets', 'crunchy'],
    isVeg: true,
    isBestseller: false,
    preparationTime: 10,
  },
  {
    name: 'Cheese Triangles',
    description: 'Crispy triangle pockets loaded with melted cheese',
    price: 160,
    category: catMap['quick-bites'],
    imageUrl: '/quick-bites/Cheese Triangles.jpeg',
    tags: ['cheese', 'snack', 'veg'],
    isVeg: true,
    isBestseller: false,
    preparationTime: 10,
  },
  {
    name: 'Ring Onion',
    description: 'Classic battered & fried onion rings, golden and crispy',
    price: 149,
    category: catMap['quick-bites'],
    imageUrl: '/quick-bites/Ring Onion.jpeg',
    tags: ['onion', 'rings', 'veg'],
    isVeg: true,
    isBestseller: false,
    preparationTime: 8,
  },
  {
    name: 'Chicken Nuggets',
    description: 'Juicy chicken bites with a crispy seasoned coating',
    price: 159,
    category: catMap['quick-bites'],
    imageUrl: '/quick-bites/Chicken nuggets.jpeg',
    tags: ['chicken', 'nuggets', 'crispy'],
    isVeg: false,
    isBestseller: true,
    preparationTime: 12,
  },
  {
    name: 'Popcorn',
    description: 'Light and fluffy seasoned popcorn, perfect for snacking',
    price: 169,
    category: catMap['quick-bites'],
    imageUrl: '/quick-bites/Popcorn.jpeg',
    tags: ['snack', 'light', 'veg'],
    isVeg: true,
    isBestseller: false,
    preparationTime: 5,
  },
  // ── Loaded Fries ──
  {
    name: 'Loaded corn cheese Fries',
    description: 'Golden fries generously smothered in melted cheese and sweet golden corn',
    price: 199,
    category: catMap['loaded-fries'],
    imageUrl: '/loaded-fries/Corn cheese Fries.jpeg',
    tags: ['loaded', 'cheese', 'corn'],
    isVeg: true,
    isBestseller: true,
    preparationTime: 10,
  },
  {
    name: 'Chicken loaded fries',
    description: 'Crispy fries topped with seasoned shredded chicken, melted cheese and special sauce',
    price: 199,
    category: catMap['loaded-fries'],
    imageUrl: '/loaded-fries/Chicken loaded fries.jpeg',
    tags: ['loaded', 'chicken', 'crispy'],
    isVeg: false,
    isBestseller: true,
    preparationTime: 12,
  },
  {
    name: 'Peri peri chicken Loaded fries',
    description: 'Fiery peri peri spiced fries loaded with spicy chicken chunks and rich cheese dressing',
    price: 229,
    category: catMap['loaded-fries'],
    imageUrl: '/loaded-fries/Peri peri chicken Loaded fries.jpeg',
    tags: ['spicy', 'peri-peri', 'chicken'],
    isVeg: false,
    isBestseller: true,
    preparationTime: 12,
  },
  // ── Crispy chicken ──
  {
    name: 'Crispy chicken strips 4pcs',
    description: 'Tender chicken inner fillets in an ultra-crispy golden crust',
    price: 199,
    category: catMap['crispy-chicken'],
    imageUrl: '/crispy-chicken/Crispy chicken strips.jpeg',
    tags: ['crispy', 'strips', 'chicken'],
    isVeg: false,
    isBestseller: true,
    preparationTime: 12,
  },
  {
    name: 'Peri peri chicken strips 4pcs',
    description: 'Crispy chicken tenders coated in fiery peri peri seasoning',
    price: 219,
    category: catMap['crispy-chicken'],
    imageUrl: '/crispy-chicken/Peri peri chicken strips.jpeg',
    tags: ['spicy', 'peri-peri', 'strips'],
    isVeg: false,
    isBestseller: false,
    preparationTime: 12,
  },
  {
    name: 'Crispy chicken lollipop 4pcs',
    description: 'Crispy fried chicken drumettes served with tangy dip',
    price: 199,
    category: catMap['crispy-chicken'],
    imageUrl: '/crispy-chicken/Crispy chicken lollipop.jpeg',
    tags: ['crispy', 'lollipop', 'chicken'],
    isVeg: false,
    isBestseller: true,
    preparationTime: 15,
  },
  {
    name: 'Peri peri chicken lollipop 4pcs',
    description: 'Juicy chicken lollipops dusted with hot peri peri spices',
    price: 219,
    category: catMap['crispy-chicken'],
    imageUrl: '/crispy-chicken/Peri peri chicken lollipop.jpeg',
    tags: ['spicy', 'peri-peri', 'lollipop'],
    isVeg: false,
    isBestseller: false,
    preparationTime: 15,
  },
  {
    name: 'Crispy chicken wings 4pcs',
    description: 'Golden fried crunchy chicken wings seasoned to perfection',
    price: 199,
    category: catMap['crispy-chicken'],
    imageUrl: '/crispy-chicken/Crispy chicken wings.jpeg',
    tags: ['crispy', 'wings', 'chicken'],
    isVeg: false,
    isBestseller: true,
    preparationTime: 15,
  },
  {
    name: 'Peri peri chicken wings 4pcs',
    description: 'Spicy peri peri glazed chicken wings packed with bold flavour',
    price: 219,
    category: catMap['crispy-chicken'],
    imageUrl: '/crispy-chicken/Peri peri chicken wings.jpeg',
    tags: ['spicy', 'peri-peri', 'wings'],
    isVeg: false,
    isBestseller: false,
    preparationTime: 15,
  },
  {
    name: 'Dynamite chicken',
    description: 'Crispy bite-sized chicken tossed in creamy spicy dynamite sauce',
    price: 229,
    category: catMap['crispy-chicken'],
    imageUrl: '/crispy-chicken/Dynamite chicken.jpeg',
    tags: ['dynamite', 'spicy', 'chicken'],
    isVeg: false,
    isBestseller: true,
    preparationTime: 12,
  },
  // ── Burger ──
  {
    name: 'Classic veg burger',
    description: 'Crispy vegetable patty with fresh lettuce, tomatoes and house special burger mayo',
    price: 149,
    category: catMap['burger'],
    imageUrl: '/burger/Classic veg burger.jpeg',
    tags: ['veg', 'classic', 'burger'],
    isVeg: true,
    isBestseller: true,
    preparationTime: 10,
  },
  {
    name: 'Panner burger',
    description: 'Spiced golden paneer patty layered with fresh veggies and tangy mint chutney mayo',
    price: 199,
    category: catMap['burger'],
    imageUrl: '/burger/Panner burger.jpeg',
    tags: ['veg', 'paneer', 'desi'],
    isVeg: true,
    isBestseller: false,
    preparationTime: 12,
  },
  {
    name: 'Crispy Chicken Burger',
    description: 'Juicy fried chicken breast in crunchy batter topped with crisp lettuce and creamy sauce',
    price: 199,
    category: catMap['burger'],
    imageUrl: '/burger/Crispy Chicken Burger.jpeg',
    tags: ['crispy', 'chicken', 'burger'],
    isVeg: false,
    isBestseller: true,
    preparationTime: 12,
  },
  {
    name: 'Peri peri Crispy Chicken Burger',
    description: 'Crunchy chicken patty coated in spicy peri peri spice blend with zesty sauce',
    price: 219,
    category: catMap['burger'],
    imageUrl: '/burger/Peri peri Crispy Chicken Burger.jpeg',
    tags: ['spicy', 'peri-peri', 'chicken'],
    isVeg: false,
    isBestseller: false,
    preparationTime: 12,
  },
  {
    name: 'Crispy Chicken Cheese Burger',
    description: 'Golden crispy chicken burger stacked with melted cheddar cheese slice',
    price: 219,
    category: catMap['burger'],
    imageUrl: '/burger/Crispy Chicken Cheese Burger-.jpeg',
    tags: ['cheese', 'crispy', 'chicken'],
    isVeg: false,
    isBestseller: true,
    preparationTime: 12,
  },
  {
    name: 'Dynamite chicken Burger',
    description: 'Crispy chicken patty generously glazed with spicy creamy dynamite sauce',
    price: 219,
    category: catMap['burger'],
    imageUrl: '/burger/Dynamite chicken Burger.jpeg',
    tags: ['dynamite', 'spicy', 'chicken'],
    isVeg: false,
    isBestseller: false,
    preparationTime: 12,
  },
  {
    name: 'Grilled Chicken Burger',
    description: 'Flame-grilled marinated chicken breast with fresh greens and herb garlic dressing',
    price: 199,
    category: catMap['burger'],
    imageUrl: '/burger/Grilled Chicken Burger.jpeg',
    tags: ['grilled', 'healthy', 'chicken'],
    isVeg: false,
    isBestseller: false,
    preparationTime: 12,
  },
  // ── Sandwich ──
  {
    name: 'Veg Grilled Sandwich',
    description: 'Toasted bread loaded with sliced fresh veggies, herbs and cheese spread',
    price: 149,
    category: catMap['sandwich'],
    imageUrl: '/sandwich/Veg Grilled Sandwich.jpeg',
    tags: ['veg', 'grilled', 'sandwich'],
    isVeg: true,
    isBestseller: true,
    preparationTime: 8,
  },
  {
    name: 'Egg Sandwich',
    description: 'Fluffy seasoned egg omelette with crispy veggies and pepper mayo',
    price: 149,
    category: catMap['sandwich'],
    imageUrl: '/sandwich/Egg Sandwich.jpeg',
    tags: ['egg', 'sandwich', 'protein'],
    isVeg: false,
    isBestseller: false,
    preparationTime: 8,
  },
  {
    name: 'Corn Cheese Sandwich',
    description: 'Golden sweet corn and abundant melted cheese in grilled golden bread',
    price: 199,
    category: catMap['sandwich'],
    imageUrl: '/sandwich/Corn Cheese Sandwich.jpeg',
    tags: ['veg', 'corn', 'cheese'],
    isVeg: true,
    isBestseller: true,
    preparationTime: 10,
  },
  {
    name: 'Panner Tikka Sandwich',
    description: 'Marinated spiced paneer tikka cubes with mint mayo and bell peppers',
    price: 199,
    category: catMap['sandwich'],
    imageUrl: '/sandwich/Panner Tikka Sandwich.jpeg',
    tags: ['veg', 'paneer', 'desi'],
    isVeg: true,
    isBestseller: false,
    preparationTime: 10,
  },
  {
    name: 'Grilled Chicken Sandwich',
    description: 'Juicy herb-grilled chicken breast slices with fresh greens and light mayo',
    price: 199,
    category: catMap['sandwich'],
    imageUrl: '/sandwich/Grilled Chicken Sandwich.jpeg',
    tags: ['chicken', 'grilled', 'healthy'],
    isVeg: false,
    isBestseller: true,
    preparationTime: 10,
  },
  {
    name: 'Grilled chicken Cheese sandwich',
    description: 'Herb grilled chicken and double cheddar cheese melted to perfection',
    price: 219,
    category: catMap['sandwich'],
    imageUrl: '/sandwich/Grilled chicken Cheese sandwich.jpeg',
    tags: ['chicken', 'cheese', 'grilled'],
    isVeg: false,
    isBestseller: true,
    preparationTime: 10,
  },
  {
    name: 'Fried Chicken Sandwich',
    description: 'Crispy golden fried chicken fillet with crunchy lettuce and special sauce',
    price: 199,
    category: catMap['sandwich'],
    imageUrl: '/sandwich/Fried Chicken Sandwich.jpeg',
    tags: ['chicken', 'fried', 'crispy'],
    isVeg: false,
    isBestseller: false,
    preparationTime: 12,
  },
  {
    name: 'Fried Chicken Cheese Sandwich',
    description: 'Crispy golden fried chicken topped with gooey melted cheese slice',
    price: 219,
    category: catMap['sandwich'],
    imageUrl: '/sandwich/Fried Chicken Cheese Sandwich.jpeg',
    tags: ['chicken', 'cheese', 'crispy'],
    isVeg: false,
    isBestseller: false,
    preparationTime: 12,
  },
  {
    name: 'Dynamite chicken sandwich',
    description: 'Crispy chicken tossed in fiery creamy dynamite sauce in grilled bread',
    price: 219,
    category: catMap['sandwich'],
    imageUrl: '/sandwich/Dynamite chicken sandwic.jpeg',
    tags: ['dynamite', 'spicy', 'chicken'],
    isVeg: false,
    isBestseller: true,
    preparationTime: 10,
  },
  // ── Roll & Wrap ──
  {
    name: 'Veg Roll',
    description: 'Crispy golden potato filling rolled in a soft flour tortilla with mint chutney',
    price: 149,
    category: catMap['roll-and-wrap'],
    imageUrl: '/roll-and-wrap/Veg Roll.jpeg',
    tags: ['veg', 'roll', 'crispy'],
    isVeg: true,
    isBestseller: true,
    preparationTime: 8,
  },
  {
    name: 'Peri peri Veg Roll',
    description: 'Peri peri spiced veggie filling wrapped in a soft tortilla',
    price: 169,
    category: catMap['roll-and-wrap'],
    imageUrl: '/roll-and-wrap/Peri peri Veg Roll.jpeg',
    tags: ['veg', 'peri-peri', 'spicy'],
    isVeg: true,
    isBestseller: false,
    preparationTime: 8,
  },
  {
    name: 'Veg Cheese Roll',
    description: 'Fresh veggies and melted cheese wrapped in a toasted flour roll',
    price: 169,
    category: catMap['roll-and-wrap'],
    imageUrl: '/roll-and-wrap/Veg Cheese Roll.jpeg',
    tags: ['veg', 'cheese', 'roll'],
    isVeg: true,
    isBestseller: false,
    preparationTime: 8,
  },
  {
    name: 'Panner Roll',
    description: 'Spiced paneer pieces with onions and chutneys in a soft roll',
    price: 199,
    category: catMap['roll-and-wrap'],
    imageUrl: '/roll-and-wrap/Panner Roll.jpeg',
    tags: ['veg', 'paneer', 'roll'],
    isVeg: true,
    isBestseller: true,
    preparationTime: 10,
  },
  {
    name: 'Peri peri Panner Roll',
    description: 'Peri peri marinated paneer rolled with crunchy onions and cool mint sauce',
    price: 219,
    category: catMap['roll-and-wrap'],
    imageUrl: '/roll-and-wrap/Peri peri Panner Roll.jpeg',
    tags: ['veg', 'paneer', 'peri-peri'],
    isVeg: true,
    isBestseller: false,
    preparationTime: 10,
  },
  {
    name: 'Corn Cheese Roll',
    description: 'Sweet golden corn and gooey melted cheese in a crispy toasted roll',
    price: 199,
    category: catMap['roll-and-wrap'],
    imageUrl: '/roll-and-wrap/Corn Cheese Roll.jpeg',
    tags: ['veg', 'corn', 'cheese'],
    isVeg: true,
    isBestseller: true,
    preparationTime: 10,
  },
  {
    name: 'Peri peri corn Cheese Roll',
    description: 'Corn and cheese roll levelled up with fiery peri peri seasoning',
    price: 219,
    category: catMap['roll-and-wrap'],
    imageUrl: '/roll-and-wrap/Peri peri corn Cheese Roll.jpeg',
    tags: ['veg', 'peri-peri', 'cheese'],
    isVeg: true,
    isBestseller: false,
    preparationTime: 10,
  },
  {
    name: 'Crispy Chicken Wrap',
    description: 'Golden crispy fried chicken strips wrapped with fresh lettuce and creamy sauce',
    price: 199,
    category: catMap['roll-and-wrap'],
    imageUrl: '/roll-and-wrap/Crispy Chicken Wrap.jpeg',
    tags: ['chicken', 'crispy', 'wrap'],
    isVeg: false,
    isBestseller: true,
    preparationTime: 10,
  },
  {
    name: 'Peri peri Chicken Wrap',
    description: 'Spicy peri peri chicken strips with crunchy veggies and cool sauce',
    price: 219,
    category: catMap['roll-and-wrap'],
    imageUrl: '/roll-and-wrap/Peri peri Chicken Wrap.jpeg',
    tags: ['chicken', 'peri-peri', 'spicy'],
    isVeg: false,
    isBestseller: false,
    preparationTime: 10,
  },
  {
    name: 'Grilled Chicken Wrap',
    description: 'Juicy herb-grilled chicken breast with fresh greens and garlic mayo',
    price: 199,
    category: catMap['roll-and-wrap'],
    imageUrl: '/roll-and-wrap/Grilled Chicken Wrap.jpeg',
    tags: ['chicken', 'grilled', 'healthy'],
    isVeg: false,
    isBestseller: true,
    preparationTime: 10,
  },
  {
    name: 'Peri peri Grilled Chicken Wrap',
    description: 'Peri peri spiced grilled chicken with crunchy slaw and tangy sauce',
    price: 219,
    category: catMap['roll-and-wrap'],
    imageUrl: '/roll-and-wrap/Peri peri Grilled Chicken Wrap.jpeg',
    tags: ['chicken', 'peri-peri', 'grilled'],
    isVeg: false,
    isBestseller: false,
    preparationTime: 10,
  },
  {
    name: 'BBQ Chicken Wrap',
    description: 'Smoky BBQ glazed chicken strips with cheddar, lettuce and chipotle mayo',
    price: 219,
    category: catMap['roll-and-wrap'],
    imageUrl: '/roll-and-wrap/BBQ Chicken Wrap.jpeg',
    tags: ['chicken', 'bbq', 'smoky'],
    isVeg: false,
    isBestseller: true,
    preparationTime: 10,
  },
  {
    name: 'Dynamite Chicken Wrap',
    description: 'Crispy chicken in fiery dynamite sauce wrapped with crunchy veggies',
    price: 219,
    category: catMap['roll-and-wrap'],
    imageUrl: '/roll-and-wrap/Dynamite Chicken Wrap.jpeg',
    tags: ['chicken', 'dynamite', 'spicy'],
    isVeg: false,
    isBestseller: true,
    preparationTime: 10,
  },
  // ── Korean ──
  {
    name: 'Korean Chicken Fries',
    description: 'Crispy seasoned french fries topped with Korean glazed chicken chunks and scallions',
    price: 219,
    category: catMap['korean'],
    imageUrl: '/korean/Korean Chicken Fries.jpeg',
    tags: ['korean', 'chicken', 'fries', 'crispy'],
    isVeg: false,
    isBestseller: true,
    preparationTime: 10,
  },
  {
    name: 'Korean Chicken Burger',
    description: 'Crunchy chicken thigh dipped in sweet & spicy gochujang glaze with kimchi slaw',
    price: 219,
    category: catMap['korean'],
    imageUrl: '/korean/Korean Chicken Burger.jpeg',
    tags: ['korean', 'chicken', 'burger', 'spicy'],
    isVeg: false,
    isBestseller: true,
    preparationTime: 12,
  },
  {
    name: 'Korean Chicken Sandwich',
    description: 'Toasted gourmet sandwich stuffed with sweet-spicy Korean chicken and melted cheese',
    price: 219,
    category: catMap['korean'],
    imageUrl: '/korean/Korean Chicken Sandwich.jpeg',
    tags: ['korean', 'chicken', 'sandwich'],
    isVeg: false,
    isBestseller: false,
    preparationTime: 10,
  },
  {
    name: 'Korean Chicken Wrap',
    description: 'Soft tortilla rolled with fiery Korean chicken strips, crisp cucumber and sesame mayo',
    price: 219,
    category: catMap['korean'],
    imageUrl: '/korean/Korean Chicken Wrap.jpeg',
    tags: ['korean', 'chicken', 'wrap'],
    isVeg: false,
    isBestseller: false,
    preparationTime: 10,
  },
  {
    name: 'Korean Ramen veg noodles',
    description: 'Authentic Korean style spicy instant noodles with fresh mixed veggies and savory broth',
    price: 199,
    category: catMap['korean'],
    imageUrl: '/korean/Korean Ramen veg noodles.jpeg',
    tags: ['korean', 'ramen', 'veg', 'noodles'],
    isVeg: true,
    isBestseller: true,
    preparationTime: 10,
  },
  {
    name: 'Korean Ramen panner noodles',
    description: 'Fiery Korean broth ramen noodles topped with golden paneer cubes and herbs',
    price: 219,
    category: catMap['korean'],
    imageUrl: '/korean/Korean Ramen panner noodles.jpeg',
    tags: ['korean', 'ramen', 'paneer', 'noodles'],
    isVeg: true,
    isBestseller: false,
    preparationTime: 12,
  },
  {
    name: 'Korean Ramen chicken noodles',
    description: 'Hearty spicy Korean ramen loaded with tender chicken pieces, scallions and boiled egg',
    price: 219,
    category: catMap['korean'],
    imageUrl: '/korean/Korean Ramen chicken noodles.jpeg',
    tags: ['korean', 'ramen', 'chicken', 'noodles'],
    isVeg: false,
    isBestseller: true,
    preparationTime: 12,
  },
  // ── Pasta & Pulao ──
  {
    name: 'Alfredo veg Pasta',
    description: 'Creamy white sauce penne pasta loaded with garlic, herbs and sauteed garden veggies',
    price: 199,
    category: catMap['pasta-and-pulao'],
    imageUrl: '/pasta-and-pulao/Alfredo veg Pasta.jpeg',
    tags: ['pasta', 'alfredo', 'creamy', 'veg'],
    isVeg: true,
    isBestseller: true,
    preparationTime: 12,
  },
  {
    name: 'Alfredo Egg pasta',
    description: 'Rich and velvety Alfredo pasta tossed with seasoned boiled egg slices and parmesan',
    price: 229,
    category: catMap['pasta-and-pulao'],
    imageUrl: '/pasta-and-pulao/Alfredo Egg pasta.jpeg',
    tags: ['pasta', 'alfredo', 'egg'],
    isVeg: false,
    isBestseller: false,
    preparationTime: 12,
  },
  {
    name: 'Alfredo Panner pasta',
    description: 'Silky smooth Alfredo cream sauce pasta topped with spiced golden paneer cubes',
    price: 219,
    category: catMap['pasta-and-pulao'],
    imageUrl: '/pasta-and-pulao/Alfredo Panner pasta.jpeg',
    tags: ['pasta', 'alfredo', 'paneer', 'veg'],
    isVeg: true,
    isBestseller: false,
    preparationTime: 12,
  },
  {
    name: 'Alfredo chicken pasta',
    description: 'Tender juicy chicken chunks in an indulgent creamy garlic cheese Alfredo sauce',
    price: 219,
    category: catMap['pasta-and-pulao'],
    imageUrl: '/pasta-and-pulao/Alfredo chicken pasta.jpeg',
    tags: ['pasta', 'alfredo', 'chicken'],
    isVeg: false,
    isBestseller: true,
    preparationTime: 14,
  },
  {
    name: 'Veg pulao',
    description: 'Aromatic basmati rice simmered with whole spices, garden vegetables and ghee',
    price: 199,
    category: catMap['pasta-and-pulao'],
    imageUrl: '/pasta-and-pulao/Veg pulao.jpeg',
    tags: ['pulao', 'rice', 'veg', 'desi'],
    isVeg: true,
    isBestseller: true,
    preparationTime: 12,
  },
  {
    name: 'Egg pulao',
    description: 'Fragrant spiced basmati rice pulao served with flavorful seasoned eggs and raita',
    price: 229,
    category: catMap['pasta-and-pulao'],
    imageUrl: '/pasta-and-pulao/Egg pulao.jpeg',
    tags: ['pulao', 'rice', 'egg'],
    isVeg: false,
    isBestseller: false,
    preparationTime: 12,
  },
  {
    name: 'Panner pulao',
    description: 'Royal aromatic pulao cooked with golden roasted paneer cubes and fragrant herbs',
    price: 249,
    category: catMap['pasta-and-pulao'],
    imageUrl: '/pasta-and-pulao/Panner pulao.jpeg',
    tags: ['pulao', 'rice', 'paneer', 'veg'],
    isVeg: true,
    isBestseller: false,
    preparationTime: 14,
  },
  {
    name: 'Chicken pulao',
    description: 'Succulent marinated chicken pieces slow-cooked with long grain basmati rice and rich spices',
    price: 249,
    category: catMap['pasta-and-pulao'],
    imageUrl: '/pasta-and-pulao/Chicken pulao.jpeg',
    tags: ['pulao', 'rice', 'chicken'],
    isVeg: false,
    isBestseller: true,
    preparationTime: 15,
  },
  // ── Mojitos ──
  {
    name: 'Blackcurrant Mojito',
    description: 'Cool, fizzy and refreshing blackcurrant mojito with fresh mint',
    price: 149,
    category: catMap['mojitos'],
    tags: ['cold', 'fizzy', 'blackcurrant'],
    isVeg: true,
    isBestseller: true,
    preparationTime: 5,
  },
  {
    name: 'Classic Virgin Mojito',
    description: 'Fresh lime, mint and sparkling water — timeless and refreshing',
    price: 129,
    category: catMap['mojitos'],
    tags: ['cold', 'lime', 'mint'],
    isVeg: true,
    isBestseller: false,
    preparationTime: 5,
  },
  {
    name: 'Watermelon Mojito',
    description: 'Summer-special watermelon crush with mint and lemon fizz',
    price: 159,
    category: catMap['mojitos'],
    tags: ['cold', 'watermelon', 'summer'],
    isVeg: true,
    isBestseller: false,
    preparationTime: 5,
  },
  {
    name: 'Passion Fruit Mojito',
    description: 'Tropical passion fruit with basil and sparkling water',
    price: 169,
    category: catMap['mojitos'],
    tags: ['cold', 'tropical', 'passion fruit'],
    isVeg: true,
    isBestseller: false,
    preparationTime: 5,
  },
  // ── Milkshakes ──
  {
    name: 'Buttercotch Milkshake',
    description: 'Rich, creamy and indulgent butterscotch milkshake topped with caramel drizzle',
    price: 179,
    category: catMap['milkshakes'],
    tags: ['cold', 'butterscotch', 'indulgent'],
    isVeg: true,
    isBestseller: true,
    preparationTime: 7,
  },
  {
    name: 'Classic Chocolate Milkshake',
    description: 'Thick and rich chocolate milkshake with Oreo crumble',
    price: 169,
    category: catMap['milkshakes'],
    tags: ['cold', 'chocolate', 'classic'],
    isVeg: true,
    isBestseller: false,
    preparationTime: 7,
  },
  {
    name: 'Strawberry Cheesecake Shake',
    description: 'Creamy strawberry shake blended with cheesecake chunks',
    price: 199,
    category: catMap['milkshakes'],
    tags: ['cold', 'strawberry', 'cheesecake'],
    isVeg: true,
    isBestseller: false,
    preparationTime: 8,
  },
  {
    name: 'Vanilla Bean Shake',
    description: 'Simple, elegant vanilla bean milkshake with whipped cream',
    price: 149,
    category: catMap['milkshakes'],
    tags: ['cold', 'vanilla', 'classic'],
    isVeg: true,
    isBestseller: false,
    preparationTime: 5,
  },
];

const Finance = require('./models/Finance');
const Inventory = require('./models/Inventory');

const seed = async () => {
  try {
    await connectDB();

    console.log('🗑️  Clearing existing data...');
    await Promise.all([
      User.deleteMany({}),
      Category.deleteMany({}),
      MenuItem.deleteMany({}),
      Finance.deleteMany({}),
      Inventory.deleteMany({}),
    ]);

    // ── Seed Admin User (Optional via environment variables) ──
    let adminUser = null;
    if (process.env.ADMIN_EMAIL && process.env.ADMIN_PASSWORD) {
      console.log('👤 Creating initial admin user from env credentials...');
      adminUser = await User.create({
        name: 'Dood Admin',
        email: process.env.ADMIN_EMAIL,
        passwordHash: process.env.ADMIN_PASSWORD,
        role: 'admin',
      });
    }

    // ── Seed Categories ──
    console.log('📂 Seeding categories...');
    const createdCats = await Category.insertMany(categories);
    const catMap = {};
    createdCats.forEach((c) => { catMap[c.slug] = c._id; });

    // ── Seed Menu Items ──
    console.log('🍔 Seeding menu items...');
    const menuItems = getMenuItems(catMap);
    await MenuItem.insertMany(menuItems);

    // ── Seed Inventory Stock ──
    console.log('📦 Seeding inventory stock...');
    await Inventory.insertMany([
      { name: 'Fresh Dairy Milk 1L', sku: 'MILK-WHOLE-01', category: 'dairy', quantity: 45, unit: 'L', costPerUnit: 65, reorderLevel: 15, location: 'Main Refrigerator' },
      { name: 'Espresso Arabica Coffee Beans 1kg', sku: 'BEAN-ARABICA-01', category: 'beverages', quantity: 8, unit: 'kg', costPerUnit: 850, reorderLevel: 10, location: 'Dry Store' },
      { name: 'Cheddar Cheese Slices 1kg', sku: 'CHEESE-CHEDDAR-01', category: 'dairy', quantity: 4, unit: 'kg', costPerUnit: 480, reorderLevel: 5, location: 'Main Refrigerator' },
      { name: 'Fresh Chicken Drumettes 1kg', sku: 'CHK-DRUM-01', category: 'produce', quantity: 15, unit: 'kg', costPerUnit: 260, reorderLevel: 5, location: 'Main Refrigerator' },
      { name: 'Fresh Mint Leaves', sku: 'HERB-MINT-100', category: 'produce', quantity: 2, unit: 'kg', costPerUnit: 150, reorderLevel: 3, location: 'Cold Storage' },
    ]);

    // ── Seed Finances ──
    console.log('💰 Seeding initial financial transactions...');
    const recordedById = adminUser ? adminUser._id : new mongoose.Types.ObjectId();
    await Finance.insertMany([
      { type: 'income', category: 'order_revenue', amount: 14500, description: 'Daily Order Counter Sales', recordedBy: recordedById, transactionDate: new Date() },
      { type: 'income', category: 'catering', amount: 8500, description: 'Weekend Corporate Coffee Catering', recordedBy: recordedById, transactionDate: new Date(Date.now() - 86400000) },
      { type: 'expense', category: 'ingredients', amount: 6200, description: 'Coffee beans & Dairy restock batch #401', recordedBy: recordedById, transactionDate: new Date() },
      { type: 'expense', category: 'utilities', amount: 4500, description: 'Monthly Electricity & Water Bill', recordedBy: recordedById, transactionDate: new Date(Date.now() - 172800000) },
    ]);

    console.log(`✅ Seeded categories, menu items, inventory, and finances successfully.`);
    if (adminUser) {
      console.log(`🔑 Admin created: ${process.env.ADMIN_EMAIL}`);
    } else {
      console.log(`ℹ️  No ADMIN_EMAIL/ADMIN_PASSWORD provided in env. The very first user registering via /api/v1/auth/register will automatically become the Admin.`);
    }
    process.exit(0);
  } catch (error) {
    console.error('❌ Seed error:', error);
    process.exit(1);
  }
};

seed();
